import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1772087235047 implements MigrationInterface {
    name = 'InitialMigration1772087235047'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "certifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "UQ_9eb29158fdc27b227a71c7f138c" UNIQUE ("name"), CONSTRAINT "PK_fd763d412e4a1fb1b6dadd6e72b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "farmer_product_photo_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "url" character varying NOT NULL, "publicId" character varying NOT NULL, "description" character varying NOT NULL, "mimeType" character varying, "size" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" uuid, CONSTRAINT "PK_8a9978b2c60fb313dd116a5d949" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."crop_quantity_unit_enum" AS ENUM('kilogram', 'tonne')`);
        await queryRunner.query(`CREATE TYPE "public"."events_referencetype_enum" AS ENUM('product', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."events_status_enum" AS ENUM('upcoming', 'today', 'concluded')`);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "cropQuantity" character varying, "cropQuantityUnit" "public"."crop_quantity_unit_enum", "isHarvestEvent" boolean NOT NULL DEFAULT false, "referenceId" uuid, "referenceType" "public"."events_referencetype_enum", "eventDate" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."events_status_enum" NOT NULL DEFAULT 'upcoming', "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cropId" uuid, "ownerId" uuid, "productId" uuid, CONSTRAINT "REL_355396274b2fbf7db953b9fedf" UNIQUE ("productId"), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quality_standards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "UQ_74cfbe051fbf6800d3f72cf6a5a" UNIQUE ("name"), CONSTRAINT "PK_aeac940be3b7656800253a57e5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_order_doc_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "url" character varying NOT NULL, "publicId" character varying NOT NULL, "description" character varying NOT NULL, "mimeType" character varying, "size" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "buyRequestId" uuid, CONSTRAINT "REL_fd21d9270e77e2727e39a55723" UNIQUE ("buyRequestId"), CONSTRAINT "PK_eb42f910e9e7f5ba26ba64c59f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_initiatortype_enum" AS ENUM('buyer', 'seller')`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('open', 'under_review', 'resolved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "initiatorType" "public"."disputes_initiatortype_enum" NOT NULL, "reason" text NOT NULL, "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'open', "resolvedBy" text, "resolvedAt" TIMESTAMP WITH TIME ZONE, "rejectedBy" text, "rejectedAt" TIMESTAMP WITH TIME ZONE, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "buyRequestId" uuid, "initiatedById" uuid, CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17dfc0433d332b5f6777a57618" ON "disputes" ("initiatedById") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ea46f4f2225f38d127063c367" ON "disputes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_283f3ae97432623646f4008dfa" ON "disputes" ("buyRequestId") `);
        await queryRunner.query(`CREATE TYPE "public"."ratings_raterrole_enum" AS ENUM('buyer', 'seller')`);
        await queryRunner.query(`CREATE TYPE "public"."ratings_rateerole_enum" AS ENUM('buyer', 'seller')`);
        await queryRunner.query(`CREATE TABLE "ratings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "raterRole" "public"."ratings_raterrole_enum" NOT NULL, "rateeRole" "public"."ratings_rateerole_enum" NOT NULL, "score" integer NOT NULL, "comment" text, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "buyRequestId" uuid, "raterId" uuid, "rateeId" uuid, CONSTRAINT "uq_rating_per_buyrequest_per_rater" UNIQUE ("buyRequestId", "raterId"), CONSTRAINT "PK_0f31425b073219379545ad68ed9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc83bc48cfaaa56920a68da24f" ON "ratings" ("rateeId") `);
        await queryRunner.query(`CREATE TYPE "public"."product_inventories_type_enum" AS ENUM('addition', 'reservation', 'release', 'deduction')`);
        await queryRunner.query(`CREATE TABLE "product_inventories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantityKg" numeric(30,2) NOT NULL, "type" "public"."product_inventories_type_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" uuid, "buyRequestId" uuid, CONSTRAINT "PK_7ff88ac3f0221978eea3f9f999a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."buy_requests_preferredpaymentmethod_enum" AS ENUM('pay_on_delivery', 'cash_and_carry', 'five_days_post_delivery', 'fifteen_days_post_delivery', 'thirty_days_post_delivery')`);
        await queryRunner.query(`CREATE TYPE "public"."buy_requests_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."buy_requests_orderstate_enum" AS ENUM('awaiting_shipping', 'in_transit', 'delivered', 'completed')`);
        await queryRunner.query(`CREATE TABLE "buy_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestNumber" bigint NOT NULL, "description" character varying NOT NULL, "productQuantityKg" numeric(30,2) NOT NULL, "pricePerKgOffer" numeric(30,2) NOT NULL, "estimatedDeliveryDate" TIMESTAMP WITH TIME ZONE NOT NULL, "deliveryLocation" character varying NOT NULL, "preferredPaymentMethod" "public"."buy_requests_preferredpaymentmethod_enum" NOT NULL DEFAULT 'pay_on_delivery', "status" "public"."buy_requests_status_enum" NOT NULL DEFAULT 'pending', "isGeneral" boolean NOT NULL DEFAULT false, "orderState" "public"."buy_requests_orderstate_enum", "orderStateTime" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "paymentAmount" numeric(30,2), "paymentConfirmed" boolean NOT NULL DEFAULT false, "paymentConfirmedAt" TIMESTAMP WITH TIME ZONE, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cropTypeId" uuid, "qualityStandardTypeId" uuid, "buyerId" uuid, "sellerId" uuid, "productId" uuid, CONSTRAINT "UQ_4625c99de2e8489e727f6253181" UNIQUE ("requestNumber"), CONSTRAINT "PK_5a91945843a2916ab3a8ed4854a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_pricecurrency_enum" AS ENUM('ngn')`);
        await queryRunner.query(`CREATE TYPE "public"."products_approvalstatus_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "quantityKg" numeric(30,2) NOT NULL DEFAULT '0', "reservedQuantityKg" numeric(30,2) NOT NULL DEFAULT '0', "pricePerKg" numeric(30,2) NOT NULL, "priceCurrency" "public"."products_pricecurrency_enum" NOT NULL DEFAULT 'ngn', "locationAddress" character varying, "approvalStatus" "public"."products_approvalstatus_enum" NOT NULL DEFAULT 'pending', "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cropTypeId" uuid, "ownerId" uuid, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_33e6399d4c7cedd12806d5d4dd7" UNIQUE ("name"), CONSTRAINT "PK_098dbeb7c803dc7c08a7f02b805" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" character varying NOT NULL, "url" character varying NOT NULL, "publicId" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ownerId" uuid, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_audience_enum" AS ENUM('user', 'admins', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('buy_request', 'order_status', 'contact_message', 'dispute', 'system', 'rating')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_relatedentitytype_enum" AS ENUM('buy_request', 'product', 'dispute', 'event')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('app', 'sms', 'email')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "audience" "public"."notifications_audience_enum" NOT NULL DEFAULT 'user', "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "relatedEntityType" "public"."notifications_relatedentitytype_enum" NOT NULL, "relatedEntityId" uuid, "senderId" uuid, "senderName" character varying(255), "isRead" boolean NOT NULL DEFAULT false, "channel" "public"."notifications_channel_enum" NOT NULL DEFAULT 'app', "sent" boolean NOT NULL DEFAULT false, "failureReason" text, "externalMessageId" character varying, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b73fd7027ccee0a8e006efc5af" ON "notifications" ("audience", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_21e65af2f4f242d4c85a92aff4" ON "notifications" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE TYPE "public"."users_farmsizeunit_enum" AS ENUM('hectare', 'acre')`);
        await queryRunner.query(`CREATE TYPE "public"."users_estimatedannualproductionunit_enum" AS ENUM('kilogram', 'tonne')`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('farmer', 'processor', 'admin', 'super_admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_businesstype_enum" AS ENUM('food processing', 'oil mill', 'floor mill', 'rice mill', 'cassava processing', 'fruit processing')`);
        await queryRunner.query(`CREATE TYPE "public"."users_processsingcapacityunit_enum" AS ENUM('tons')`);
        await queryRunner.query(`CREATE TYPE "public"."users_operatingdaysperweek_enum" AS ENUM('7days', '6days', '5days', 'seasonal operation')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "farmAddress" character varying, "country" character varying, "state" character varying, "farmName" character varying, "farmSize" character varying, "farmSizeUnit" "public"."users_farmsizeunit_enum", "estimatedAnnualProduction" character varying, "estimatedAnnualProductionUnit" "public"."users_estimatedannualproductionunit_enum", "farmingExperience" character varying, "internetAccess" character varying, "howUserSellCrops" character varying, "bankName" character varying, "accountNumber" character varying, "role" "public"."users_role_enum" NOT NULL, "companyName" character varying, "businessRegNumber" character varying, "yearEstablished" character varying, "businessType" "public"."users_businesstype_enum", "processsingCapacitySize" character varying, "processsingCapacityUnit" "public"."users_processsingcapacityunit_enum", "operatingDaysPerWeek" "public"."users_operatingdaysperweek_enum", "storageCapacity" character varying, "minimumOrderQuality" character varying, "OperationsType" character varying, "userVerified" boolean NOT NULL DEFAULT false, "userVerificationOtp" character varying, "userVerificationOtpExpiryTime" TIMESTAMP WITH TIME ZONE, "passwordResetToken" character varying, "passwordResetExpiryTime" TIMESTAMP WITH TIME ZONE, "passwordChangedAt" TIMESTAMP WITH TIME ZONE, "isDisabled" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_certifications" ("userId" uuid NOT NULL, "certificationId" uuid NOT NULL, CONSTRAINT "PK_f0e89ae7a987dd0bb66254528d5" PRIMARY KEY ("userId", "certificationId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_404d2600e3ff3739cc63feac3c" ON "user_certifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_61407e2dc4b10aa6577e89b473" ON "user_certifications" ("certificationId") `);
        await queryRunner.query(`CREATE TABLE "user_qualityStandards" ("userId" uuid NOT NULL, "qualityStandardId" uuid NOT NULL, CONSTRAINT "PK_54b40dfa1491e8a965c30a87fb0" PRIMARY KEY ("userId", "qualityStandardId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dcff79f8c120e7fc6356702475" ON "user_qualityStandards" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c09fdd3f5fcd395c73b291a87e" ON "user_qualityStandards" ("qualityStandardId") `);
        await queryRunner.query(`CREATE TABLE "user_crops" ("userId" uuid NOT NULL, "cropId" uuid NOT NULL, CONSTRAINT "PK_4907ab1e7faa6dd9daaed7894fb" PRIMARY KEY ("userId", "cropId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_764bc4a82f2cfd2f8ac1aeb63a" ON "user_crops" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_62f05dd8a673f7f24ff8c1279c" ON "user_crops" ("cropId") `);
        await queryRunner.query(`ALTER TABLE "farmer_product_photo_files" ADD CONSTRAINT "FK_d7ae89a079bd687a26f71c14d1c" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_d6bbb35c3b888c9cd97bb05f4c5" FOREIGN KEY ("cropId") REFERENCES "crops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_72bbe49600962f125177d7d6b68" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_355396274b2fbf7db953b9fedfa" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_doc_files" ADD CONSTRAINT "FK_fd21d9270e77e2727e39a557237" FOREIGN KEY ("buyRequestId") REFERENCES "buy_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_283f3ae97432623646f4008dfa4" FOREIGN KEY ("buyRequestId") REFERENCES "buy_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_17dfc0433d332b5f6777a576186" FOREIGN KEY ("initiatedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_bfb728df3684c90d61c5f597a2c" FOREIGN KEY ("buyRequestId") REFERENCES "buy_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_e5d0a61e726410a860f23f39de7" FOREIGN KEY ("raterId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_dc83bc48cfaaa56920a68da24ff" FOREIGN KEY ("rateeId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_inventories" ADD CONSTRAINT "FK_c444d1960e383239e953e5aee84" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_inventories" ADD CONSTRAINT "FK_45ae7a30bf33db046e5bb883f1a" FOREIGN KEY ("buyRequestId") REFERENCES "buy_requests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buy_requests" ADD CONSTRAINT "FK_3209e88dbcd92054cd9733f19ad" FOREIGN KEY ("cropTypeId") REFERENCES "crops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buy_requests" ADD CONSTRAINT "FK_0f16dab60cb308d10d39719fdf1" FOREIGN KEY ("qualityStandardTypeId") REFERENCES "quality_standards"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buy_requests" ADD CONSTRAINT "FK_b34ab9b15f8ca8d77714225c655" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buy_requests" ADD CONSTRAINT "FK_b796faf80f1e53590bef5ca9137" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buy_requests" ADD CONSTRAINT "FK_50344a787aad7c11c32b9dff917" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_3cef2468bedd7b37ab7f8c821da" FOREIGN KEY ("cropTypeId") REFERENCES "crops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_663aa9983fd61dfc310d407d4da" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a23484d1055e34d75b25f616792" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_certifications" ADD CONSTRAINT "FK_404d2600e3ff3739cc63feac3cc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_certifications" ADD CONSTRAINT "FK_61407e2dc4b10aa6577e89b4738" FOREIGN KEY ("certificationId") REFERENCES "certifications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_qualityStandards" ADD CONSTRAINT "FK_dcff79f8c120e7fc6356702475c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_qualityStandards" ADD CONSTRAINT "FK_c09fdd3f5fcd395c73b291a87ed" FOREIGN KEY ("qualityStandardId") REFERENCES "quality_standards"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_crops" ADD CONSTRAINT "FK_764bc4a82f2cfd2f8ac1aeb63a4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_crops" ADD CONSTRAINT "FK_62f05dd8a673f7f24ff8c1279c7" FOREIGN KEY ("cropId") REFERENCES "crops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_crops" DROP CONSTRAINT "FK_62f05dd8a673f7f24ff8c1279c7"`);
        await queryRunner.query(`ALTER TABLE "user_crops" DROP CONSTRAINT "FK_764bc4a82f2cfd2f8ac1aeb63a4"`);
        await queryRunner.query(`ALTER TABLE "user_qualityStandards" DROP CONSTRAINT "FK_c09fdd3f5fcd395c73b291a87ed"`);
        await queryRunner.query(`ALTER TABLE "user_qualityStandards" DROP CONSTRAINT "FK_dcff79f8c120e7fc6356702475c"`);
        await queryRunner.query(`ALTER TABLE "user_certifications" DROP CONSTRAINT "FK_61407e2dc4b10aa6577e89b4738"`);
        await queryRunner.query(`ALTER TABLE "user_certifications" DROP CONSTRAINT "FK_404d2600e3ff3739cc63feac3cc"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a23484d1055e34d75b25f616792"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_663aa9983fd61dfc310d407d4da"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_3cef2468bedd7b37ab7f8c821da"`);
        await queryRunner.query(`ALTER TABLE "buy_requests" DROP CONSTRAINT "FK_50344a787aad7c11c32b9dff917"`);
        await queryRunner.query(`ALTER TABLE "buy_requests" DROP CONSTRAINT "FK_b796faf80f1e53590bef5ca9137"`);
        await queryRunner.query(`ALTER TABLE "buy_requests" DROP CONSTRAINT "FK_b34ab9b15f8ca8d77714225c655"`);
        await queryRunner.query(`ALTER TABLE "buy_requests" DROP CONSTRAINT "FK_0f16dab60cb308d10d39719fdf1"`);
        await queryRunner.query(`ALTER TABLE "buy_requests" DROP CONSTRAINT "FK_3209e88dbcd92054cd9733f19ad"`);
        await queryRunner.query(`ALTER TABLE "product_inventories" DROP CONSTRAINT "FK_45ae7a30bf33db046e5bb883f1a"`);
        await queryRunner.query(`ALTER TABLE "product_inventories" DROP CONSTRAINT "FK_c444d1960e383239e953e5aee84"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_dc83bc48cfaaa56920a68da24ff"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_e5d0a61e726410a860f23f39de7"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_bfb728df3684c90d61c5f597a2c"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_17dfc0433d332b5f6777a576186"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_283f3ae97432623646f4008dfa4"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_doc_files" DROP CONSTRAINT "FK_fd21d9270e77e2727e39a557237"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_355396274b2fbf7db953b9fedfa"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_72bbe49600962f125177d7d6b68"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_d6bbb35c3b888c9cd97bb05f4c5"`);
        await queryRunner.query(`ALTER TABLE "farmer_product_photo_files" DROP CONSTRAINT "FK_d7ae89a079bd687a26f71c14d1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62f05dd8a673f7f24ff8c1279c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_764bc4a82f2cfd2f8ac1aeb63a"`);
        await queryRunner.query(`DROP TABLE "user_crops"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c09fdd3f5fcd395c73b291a87e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcff79f8c120e7fc6356702475"`);
        await queryRunner.query(`DROP TABLE "user_qualityStandards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61407e2dc4b10aa6577e89b473"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_404d2600e3ff3739cc63feac3c"`);
        await queryRunner.query(`DROP TABLE "user_certifications"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_operatingdaysperweek_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_processsingcapacityunit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_businesstype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_estimatedannualproductionunit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_farmsizeunit_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21e65af2f4f242d4c85a92aff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b73fd7027ccee0a8e006efc5af"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_relatedentitytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_audience_enum"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TABLE "crops"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_approvalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_pricecurrency_enum"`);
        await queryRunner.query(`DROP TABLE "buy_requests"`);
        await queryRunner.query(`DROP TYPE "public"."buy_requests_orderstate_enum"`);
        await queryRunner.query(`DROP TYPE "public"."buy_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."buy_requests_preferredpaymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "product_inventories"`);
        await queryRunner.query(`DROP TYPE "public"."product_inventories_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc83bc48cfaaa56920a68da24f"`);
        await queryRunner.query(`DROP TABLE "ratings"`);
        await queryRunner.query(`DROP TYPE "public"."ratings_rateerole_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ratings_raterrole_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_283f3ae97432623646f4008dfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ea46f4f2225f38d127063c367"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17dfc0433d332b5f6777a57618"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_initiatortype_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_order_doc_files"`);
        await queryRunner.query(`DROP TABLE "quality_standards"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TYPE "public"."events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."events_referencetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."crop_quantity_unit_enum"`);
        await queryRunner.query(`DROP TABLE "farmer_product_photo_files"`);
        await queryRunner.query(`DROP TABLE "certifications"`);
    }

}
